AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Enabled: false
  
Metrics/MethodLength: 
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false